/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdviceRouteImport } from './routes/advice'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceRoute = AdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/doctor': typeof DoctorRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/doctor': typeof DoctorRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advice': typeof AdviceRoute
  '/doctor': typeof DoctorRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/track': typeof TrackRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advice'
    | '/doctor'
    | '/emergency'
    | '/home'
    | '/insights'
    | '/profile'
    | '/settings'
    | '/timeline'
    | '/track'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advice'
    | '/doctor'
    | '/emergency'
    | '/home'
    | '/insights'
    | '/profile'
    | '/settings'
    | '/timeline'
    | '/track'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/advice'
    | '/doctor'
    | '/emergency'
    | '/home'
    | '/insights'
    | '/profile'
    | '/settings'
    | '/timeline'
    | '/track'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdviceRoute: typeof AdviceRoute
  DoctorRoute: typeof DoctorRoute
  EmergencyRoute: typeof EmergencyRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  TrackRoute: typeof TrackRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice': {
      id: '/advice'
      path: '/advice'
      fullPath: '/advice'
      preLoaderRoute: typeof AdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdviceRoute: AdviceRoute,
  DoctorRoute: DoctorRoute,
  EmergencyRoute: EmergencyRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  TrackRoute: TrackRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
